version: "3.8"

services:
  speedtest-mqtt-test:
    build: .
    container_name: speedtest-mqtt-test
    restart: unless-stopped
    env_file: .env
    network_mode: host
    environment:
      - TZ=Asia/Jerusalem
